name: dio_http_adapter
description: A customized dio HttpClientAdapter.

version: 0.1.0
homepage: https://github.com/xinthink/dio_custom_http_adapter/dio_http_adapter
repository: https://github.com/xinthink/dio_custom_http_adapter/dio_http_adapter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.0
  io_http: ^0.1.0

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0

# dependency_orverrides:
#   io_http:
#     path: ../io_http
