name: io_http
description: A customized dart:io HttpClient, mostly works with dio_http_adapter to workaround the Host verification issue during SSL handshake.

version: 0.1.0+2
homepage: https://github.com/xinthink/dio_custom_http_adapter/tree/master/io_http
repository: https://github.com/xinthink/dio_custom_http_adapter/

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
