name: check

on:
  push:
    branches:
      - master
      - 'refs/pull/*'
      - '!**/publish'
      - '!publish'

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:dev
    steps:
    - uses: actions/checkout@v1
    - name: Check io_http
      run: |
        cd io_http
        pub get && tool/check
    - name: Check dio_http_adapter
      run: |
        cd dio_http_adapter
        pub get && tool/check
