name: publish

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:dev
    steps:
    - uses: actions/checkout@v1
    - name: Prepare pub credentials
      run: echo "${{ secrets.PUB_CREDENTIALS }}" | base64 --decode > ~/.pub-cache/credentials.json
    - name: Publish io_http
      run: |
        cd io_http && pub get
        dartfmt -l 80 -w .
        pub publish --force
    - name: Publish dio_http_adapter
      run: |
        cd dio_http_adapter && pub get
        dartfmt -l 80 -w .
        pub publish --force
